import java.util.Arrays;
import java.util.List;

public class Main {
    public static void main(String[] args) {
        Dummy dummy = new Dummy();
        Directory directory = new Directory("/");
        String content = "dir ccjp\n"
                + "328708 hglnvs.bsh\n"
                + "dir hpsnpc\n"
                + "dir pcb\n"
                + "dir pntzm\n"
                + "dir pzg\n"
                + "dir thfgwwsp\n"
                + "$ cd ccjp\n"
                + "$ ls\n"
                + "159990 dlz\n"
                + "dir mbtsvblj\n"
                + "165076 nppbjl.qhg\n"
                + "$ cd mbtsvblj\n"
                + "$ ls\n"
                + "34806 frqsf.nsv\n"
                + "dir ppq\n"
                + "dir ptht\n"
                + "dir rgmvdwt\n"
                + "$ cd ppq\n"
                + "$ ls\n"
                + "266252 dhzp\n"
                + "$ cd ..\n"
                + "$ cd ptht\n"
                + "$ ls\n"
                + "dir jbnj\n"
                + "dir zcbnwhzd\n"
                + "$ cd jbnj\n"
                + "$ ls\n"
                + "dir clscr\n"
                + "145780 zwtwf.zfz\n"
                + "$ cd clscr\n"
                + "$ ls\n"
                + "249531 dhzp\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd zcbnwhzd\n"
                + "$ ls\n"
                + "dir mbtsvblj\n"
                + "$ cd mbtsvblj\n"
                + "$ ls\n"
                + "258527 pjhvzjt.brz\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd rgmvdwt\n"
                + "$ ls\n"
                + "166021 hdb\n"
                + "115350 ljpzpdbf\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd hpsnpc\n"
                + "$ ls\n"
                + "6334 bfdfbrh.vff\n"
                + "311949 qphlw.whm\n"
                + "$ cd ..\n"
                + "$ cd pcb\n"
                + "$ ls\n"
                + "dir ccjp\n"
                + "201615 gbpzf.gmg\n"
                + "dir lhth\n"
                + "319302 lrmj.rmm\n"
                + "dir mwl\n"
                + "303062 pvftq\n"
                + "$ cd ccjp\n"
                + "$ ls\n"
                + "10932 ccjp\n"
                + "80040 jjcggmr.ljs\n"
                + "299982 jrqwhsn.ptv\n"
                + "280655 ljpzpdbf\n"
                + "268430 mdvvj.dlf\n"
                + "dir mvhhlg\n"
                + "dir ppfq\n"
                + "dir rdgngdm\n"
                + "dir smftmb\n"
                + "dir tqwchhd\n"
                + "$ cd mvhhlg\n"
                + "$ ls\n"
                + "146902 fwhcbfr.shd\n"
                + "$ cd ..\n"
                + "$ cd ppfq\n"
                + "$ ls\n"
                + "263452 hdb\n"
                + "$ cd ..\n"
                + "$ cd rdgngdm\n"
                + "$ ls\n"
                + "46355 wlgshdgl\n"
                + "$ cd ..\n"
                + "$ cd smftmb\n"
                + "$ ls\n"
                + "56834 mhs\n"
                + "325038 ppmtvcj\n"
                + "dir rzcmwl\n"
                + "194645 ztwqq.jfw\n"
                + "$ cd rzcmwl\n"
                + "$ ls\n"
                + "dir btfhswwf\n"
                + "dir jrd\n"
                + "dir ndzfvl\n"
                + "$ cd btfhswwf\n"
                + "$ ls\n"
                + "62811 ccjp.clj\n"
                + "$ cd ..\n"
                + "$ cd jrd\n"
                + "$ ls\n"
                + "184948 fqqg.pfc\n"
                + "dir mshf\n"
                + "136894 nbvbr\n"
                + "$ cd mshf\n"
                + "$ ls\n"
                + "314602 ppmtvcj\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ndzfvl\n"
                + "$ ls\n"
                + "43177 hhcfpnmg.njm\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd tqwchhd\n"
                + "$ ls\n"
                + "294014 dlz\n"
                + "122061 ljpzpdbf\n"
                + "54178 ppmtvcj.wlp\n"
                + "dir trm\n"
                + "dir zcbnwhzd\n"
                + "$ cd trm\n"
                + "$ ls\n"
                + "279737 ccjp.mhz\n"
                + "$ cd ..\n"
                + "$ cd zcbnwhzd\n"
                + "$ ls\n"
                + "88477 dhnwjlzj\n"
                + "143989 dhzp\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd lhth\n"
                + "$ ls\n"
                + "79532 tlls\n"
                + "$ cd ..\n"
                + "$ cd mwl\n"
                + "$ ls\n"
                + "dir frc\n"
                + "dir lqqqppm\n"
                + "178576 prpjmrw\n"
                + "$ cd frc\n"
                + "$ ls\n"
                + "dir cvm\n"
                + "244013 dhzp\n"
                + "29325 gnh\n"
                + "264555 hdb\n"
                + "$ cd cvm\n"
                + "$ ls\n"
                + "196619 hhcfpnmg.njm\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd lqqqppm\n"
                + "$ ls\n"
                + "dir jdznl\n"
                + "38505 nqv\n"
                + "$ cd jdznl\n"
                + "$ ls\n"
                + "85492 ctt\n"
                + "228912 dfbgtqj.vsb\n"
                + "136077 nnwgd.vjn\n"
                + "254459 zrrzsfss\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd pntzm\n"
                + "$ ls\n"
                + "dir hnnhdd\n"
                + "dir mbtsvblj\n"
                + "dir vmdlwdj\n"
                + "$ cd hnnhdd\n"
                + "$ ls\n"
                + "35908 fjp\n"
                + "119221 ljpzpdbf\n"
                + "210488 whhpztz.lgt\n"
                + "$ cd ..\n"
                + "$ cd mbtsvblj\n"
                + "$ ls\n"
                + "dir clfpc\n"
                + "dir csqcnmtc\n"
                + "18524 mbtsvblj\n"
                + "dir zcrrtlh\n"
                + "$ cd clfpc\n"
                + "$ ls\n"
                + "dir jffq\n"
                + "dir qpsfrhld\n"
                + "89569 tdzfqpz.wvs\n"
                + "$ cd jffq\n"
                + "$ ls\n"
                + "dir dpngpgr\n"
                + "dir htbf\n"
                + "$ cd dpngpgr\n"
                + "$ ls\n"
                + "128899 ccjp.nbs\n"
                + "$ cd ..\n"
                + "$ cd htbf\n"
                + "$ ls\n"
                + "90381 ljpzpdbf\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd qpsfrhld\n"
                + "$ ls\n"
                + "dir bgrb\n"
                + "dir ddtlcfz\n"
                + "54115 dlz\n"
                + "154299 hhcfpnmg.njm\n"
                + "59452 jwc.pwg\n"
                + "dir mbtsvblj\n"
                + "$ cd bgrb\n"
                + "$ ls\n"
                + "119046 ccjp.zmf\n"
                + "dir qsnng\n"
                + "$ cd qsnng\n"
                + "$ ls\n"
                + "195412 vjdh.cqv\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ddtlcfz\n"
                + "$ ls\n"
                + "dir ftfch\n"
                + "26717 mbtsvblj\n"
                + "157679 mbtsvblj.rfb\n"
                + "299928 qmg\n"
                + "dir trq\n"
                + "dir wjhjlpr\n"
                + "$ cd ftfch\n"
                + "$ ls\n"
                + "50242 dhzp\n"
                + "58846 dlz\n"
                + "dir hhwsrzhv\n"
                + "$ cd hhwsrzhv\n"
                + "$ ls\n"
                + "dir bjnn\n"
                + "67610 dhzp\n"
                + "dir mbtsvblj\n"
                + "205664 tmcfmshb\n"
                + "$ cd bjnn\n"
                + "$ ls\n"
                + "199806 dlz\n"
                + "$ cd ..\n"
                + "$ cd mbtsvblj\n"
                + "$ ls\n"
                + "dir ffzjcshp\n"
                + "$ cd ffzjcshp\n"
                + "$ ls\n"
                + "dir ppmtvcj\n"
                + "$ cd ppmtvcj\n"
                + "$ ls\n"
                + "184744 dlz\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd trq\n"
                + "$ ls\n"
                + "278471 ccjp\n"
                + "$ cd ..\n"
                + "$ cd wjhjlpr\n"
                + "$ ls\n"
                + "dir wzwqrfhv\n"
                + "$ cd wzwqrfhv\n"
                + "$ ls\n"
                + "262877 ccjp\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd mbtsvblj\n"
                + "$ ls\n"
                + "243142 ccjp.szb\n"
                + "306673 lmstdpfc.nww\n"
                + "dir nlsprnh\n"
                + "dir nmzwtwwc\n"
                + "dir rbpbl\n"
                + "$ cd nlsprnh\n"
                + "$ ls\n"
                + "200708 stbjphg.hcs\n"
                + "$ cd ..\n"
                + "$ cd nmzwtwwc\n"
                + "$ ls\n"
                + "323366 vzq.pcj\n"
                + "$ cd ..\n"
                + "$ cd rbpbl\n"
                + "$ ls\n"
                + "59872 fmnmsjr.svf\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd csqcnmtc\n"
                + "$ ls\n"
                + "16652 ccjp\n"
                + "dir fsfd\n"
                + "37144 hdb\n"
                + "dir mbtsvblj\n"
                + "dir mwl\n"
                + "66387 nljlpbjq\n"
                + "dir ppmtvcj\n"
                + "120839 rgclgwnq\n"
                + "$ cd fsfd\n"
                + "$ ls\n"
                + "105721 qqvchq.mwh\n"
                + "$ cd ..\n"
                + "$ cd mbtsvblj\n"
                + "$ ls\n"
                + "dir cdzgtll\n"
                + "dir dfgd\n"
                + "dir fbfr\n"
                + "165975 mbtsvblj\n"
                + "174541 ppmtvcj\n"
                + "dir vwgrpswj\n"
                + "$ cd cdzgtll\n"
                + "$ ls\n"
                + "163523 dhzp\n"
                + "124219 dlz\n"
                + "199796 hdb\n"
                + "$ cd ..\n"
                + "$ cd dfgd\n"
                + "$ ls\n"
                + "173064 ccjp.cbt\n"
                + "dir cdqc\n"
                + "dir fzrm\n"
                + "dir grcs\n"
                + "87000 mbtsvblj.zrl\n"
                + "dir njvgs\n"
                + "dir ppmtvcj\n"
                + "210984 rhtslcwt.wgt\n"
                + "dir vws\n"
                + "$ cd cdqc\n"
                + "$ ls\n"
                + "178924 hdb\n"
                + "$ cd ..\n"
                + "$ cd fzrm\n"
                + "$ ls\n"
                + "dir bjwtbc\n"
                + "211229 dhzp\n"
                + "dir dtslj\n"
                + "76461 mbtsvblj.mtw\n"
                + "317618 mmz.mqq\n"
                + "dir mwl\n"
                + "163587 vwgq\n"
                + "$ cd bjwtbc\n"
                + "$ ls\n"
                + "9891 hhcfpnmg.njm\n"
                + "dir mwl\n"
                + "$ cd mwl\n"
                + "$ ls\n"
                + "203337 glwp.dls\n"
                + "112753 mwl.qph\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd dtslj\n"
                + "$ ls\n"
                + "277817 hhcfpnmg.njm\n"
                + "$ cd ..\n"
                + "$ cd mwl\n"
                + "$ ls\n"
                + "90781 mhnrwpmg.svv\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd grcs\n"
                + "$ ls\n"
                + "286144 rnfqhs\n"
                + "$ cd ..\n"
                + "$ cd njvgs\n"
                + "$ ls\n"
                + "dir bmhdth\n"
                + "dir ccjp\n"
                + "dir mwl\n"
                + "$ cd bmhdth\n"
                + "$ ls\n"
                + "154455 ppmtvcj.hwq\n"
                + "$ cd ..\n"
                + "$ cd ccjp\n"
                + "$ ls\n"
                + "215864 fcwjtzhs.vqn\n"
                + "$ cd ..\n"
                + "$ cd mwl\n"
                + "$ ls\n"
                + "139000 fnjztz\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ppmtvcj\n"
                + "$ ls\n"
                + "45041 jzfnmdw.jms\n"
                + "dir zstzfs\n"
                + "$ cd zstzfs\n"
                + "$ ls\n"
                + "dir qsfsj\n"
                + "$ cd qsfsj\n"
                + "$ ls\n"
                + "34771 rsv\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd vws\n"
                + "$ ls\n"
                + "98036 pjs\n"
                + "103603 szszjfv\n"
                + "211083 ztd\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd fbfr\n"
                + "$ ls\n"
                + "dir dshrpf\n"
                + "216109 hbw.jhj\n"
                + "319355 hdhl\n"
                + "dir ltf\n"
                + "210950 qstlgvb\n"
                + "dir thhncv\n"
                + "316300 zfgh\n"
                + "$ cd dshrpf\n"
                + "$ ls\n"
                + "dir nll\n"
                + "dir qrsg\n"
                + "$ cd nll\n"
                + "$ ls\n"
                + "45935 flmvswv.rll\n"
                + "4161 hhcfpnmg.njm\n"
                + "82301 sww.dwj\n"
                + "dir tqdmtp\n"
                + "46608 tzrn.qrt\n"
                + "101463 zcbnwhzd.mpm\n"
                + "$ cd tqdmtp\n"
                + "$ ls\n"
                + "280430 dhzp\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd qrsg\n"
                + "$ ls\n"
                + "dir htrvnvz\n"
                + "$ cd htrvnvz\n"
                + "$ ls\n"
                + "dir mbtsvblj\n"
                + "$ cd mbtsvblj\n"
                + "$ ls\n"
                + "235270 dlz\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ltf\n"
                + "$ ls\n"
                + "dir pcbc\n"
                + "dir wwjnwbjj\n"
                + "dir zcbnwhzd\n"
                + "$ cd pcbc\n"
                + "$ ls\n"
                + "140010 mbtsvblj.hqd\n"
                + "$ cd ..\n"
                + "$ cd wwjnwbjj\n"
                + "$ ls\n"
                + "dir mwl\n"
                + "$ cd mwl\n"
                + "$ ls\n"
                + "dir pddbdp\n"
                + "$ cd pddbdp\n"
                + "$ ls\n"
                + "27497 dlz\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd zcbnwhzd\n"
                + "$ ls\n"
                + "302364 nrgpwm.cbb\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd thhncv\n"
                + "$ ls\n"
                + "299769 hdb\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd vwgrpswj\n"
                + "$ ls\n"
                + "dir jgt\n"
                + "dir mwl\n"
                + "293673 mwl.pwl\n"
                + "$ cd jgt\n"
                + "$ ls\n"
                + "282773 hhcfpnmg.njm\n"
                + "$ cd ..\n"
                + "$ cd mwl\n"
                + "$ ls\n"
                + "288944 jfnjdtr.ssj\n"
                + "186368 wfr\n"
                + "dir zrtvvf\n"
                + "$ cd zrtvvf\n"
                + "$ ls\n"
                + "82162 gtz.gsc\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd mwl\n"
                + "$ ls\n"
                + "98218 htc.qjr\n"
                + "dir mghhqrtn\n"
                + "dir qct\n"
                + "$ cd mghhqrtn\n"
                + "$ ls\n"
                + "220446 dlz\n"
                + "36230 pwwlwv.crn\n"
                + "$ cd ..\n"
                + "$ cd qct\n"
                + "$ ls\n"
                + "33534 hdb\n"
                + "27140 jpwqvbs.mvr\n"
                + "60637 mlqtp\n"
                + "12143 nlvtp.qjn\n"
                + "152733 nqjqzt\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ppmtvcj\n"
                + "$ ls\n"
                + "dir ccjp\n"
                + "297245 zcbnwhzd\n"
                + "$ cd ccjp\n"
                + "$ ls\n"
                + "128473 wcw.dng\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd zcrrtlh\n"
                + "$ ls\n"
                + "27488 bcbnmhq\n"
                + "dir dhsmmlt\n"
                + "dir fgqbpcn\n"
                + "$ cd dhsmmlt\n"
                + "$ ls\n"
                + "42514 cvfwqnfl\n"
                + "252570 dlz\n"
                + "145814 ppmtvcj.snb\n"
                + "294613 rslsh.slv\n"
                + "186477 vwd.spz\n"
                + "dir wffbp\n"
                + "$ cd wffbp\n"
                + "$ ls\n"
                + "dir mbtsvblj\n"
                + "dir nvq\n"
                + "150447 ppmtvcj.hzc\n"
                + "34904 whzpsbqp.clq\n"
                + "dir zcbnwhzd\n"
                + "$ cd mbtsvblj\n"
                + "$ ls\n"
                + "65132 cmmlw.bmq\n"
                + "310866 cqrtmpdp.pjq\n"
                + "dir mbtsvblj\n"
                + "212527 mbtsvblj.spw\n"
                + "232198 ngmltt.qwl\n"
                + "dir pbqh\n"
                + "dir ppwgsp\n"
                + "dir qqfsb\n"
                + "223322 tzsmvh\n"
                + "$ cd mbtsvblj\n"
                + "$ ls\n"
                + "dir bzpdz\n"
                + "dir mbtsvblj\n"
                + "dir pwnn\n"
                + "dir zcbnwhzd\n"
                + "$ cd bzpdz\n"
                + "$ ls\n"
                + "272769 gtmftv\n"
                + "280597 hhcfpnmg.njm\n"
                + "151008 nmgvrhr.mvp\n"
                + "$ cd ..\n"
                + "$ cd mbtsvblj\n"
                + "$ ls\n"
                + "64862 czn\n"
                + "309781 dhzp\n"
                + "253325 dlz\n"
                + "dir dqnr\n"
                + "dir fgd\n"
                + "139779 ghtzv\n"
                + "255567 rml.rhm\n"
                + "dir srfzjfw\n"
                + "$ cd dqnr\n"
                + "$ ls\n"
                + "302986 cjnwm.lrb\n"
                + "158871 frhjlp.rnn\n"
                + "180385 nrlmq\n"
                + "$ cd ..\n"
                + "$ cd fgd\n"
                + "$ ls\n"
                + "158213 msjrcl.dsh\n"
                + "$ cd ..\n"
                + "$ cd srfzjfw\n"
                + "$ ls\n"
                + "dir jfnd\n"
                + "210830 ljpzpdbf\n"
                + "dir mbtsvblj\n"
                + "dir zcrrvpg\n"
                + "$ cd jfnd\n"
                + "$ ls\n"
                + "300883 zvtdj.srv\n"
                + "$ cd ..\n"
                + "$ cd mbtsvblj\n"
                + "$ ls\n"
                + "287467 cjdm.whc\n"
                + "233084 hpfgtnts\n"
                + "dir zcbnwhzd\n"
                + "$ cd zcbnwhzd\n"
                + "$ ls\n"
                + "79744 dlz\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd zcrrvpg\n"
                + "$ ls\n"
                + "dir jrbcqlct\n"
                + "dir srpm\n"
                + "$ cd jrbcqlct\n"
                + "$ ls\n"
                + "325945 dlz\n"
                + "$ cd ..\n"
                + "$ cd srpm\n"
                + "$ ls\n"
                + "90698 ngw.fhm\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd pwnn\n"
                + "$ ls\n"
                + "104826 ppmtvcj.jtm\n"
                + "$ cd ..\n"
                + "$ cd zcbnwhzd\n"
                + "$ ls\n"
                + "145508 fnr.dgt\n"
                + "256683 gwdl.vfl\n"
                + "dir mdv\n"
                + "44255 mqdv.cdb\n"
                + "79723 rgvcf\n"
                + "dir sjdh\n"
                + "88945 wdgq.hfm\n"
                + "dir zpm\n"
                + "$ cd mdv\n"
                + "$ ls\n"
                + "231290 dlz\n"
                + "3468 hdb\n"
                + "95091 mcm\n"
                + "67779 mwl.ncb\n"
                + "dir ppf\n"
                + "dir rfwwtjdn\n"
                + "143730 slrv.qdl\n"
                + "dir sqbdvppf\n"
                + "$ cd ppf\n"
                + "$ ls\n"
                + "73809 rgdtlp\n"
                + "$ cd ..\n"
                + "$ cd rfwwtjdn\n"
                + "$ ls\n"
                + "255306 dhzp\n"
                + "306865 zbnmtcgr.ddf\n"
                + "237019 zcbnwhzd.szn\n"
                + "$ cd ..\n"
                + "$ cd sqbdvppf\n"
                + "$ ls\n"
                + "dir ccjp\n"
                + "dir mbtsvblj\n"
                + "142955 str\n"
                + "dir whtrbcqn\n"
                + "93407 zcbnwhzd.ctr\n"
                + "$ cd ccjp\n"
                + "$ ls\n"
                + "29914 cwtvtcnp.tft\n"
                + "295537 rvlb\n"
                + "$ cd ..\n"
                + "$ cd mbtsvblj\n"
                + "$ ls\n"
                + "262652 ccjp.wbn\n"
                + "297839 mbtsvblj.gnz\n"
                + "249019 pqsqjg.vwr\n"
                + "$ cd ..\n"
                + "$ cd whtrbcqn\n"
                + "$ ls\n"
                + "dir ccjp\n"
                + "dir hslmvvb\n"
                + "51040 vzcsfcwf\n"
                + "$ cd ccjp\n"
                + "$ ls\n"
                + "39489 slps\n"
                + "$ cd ..\n"
                + "$ cd hslmvvb\n"
                + "$ ls\n"
                + "148628 gpwnf.qtd\n"
                + "dir jrl\n"
                + "11814 qtjtsvgg.ltz\n"
                + "$ cd jrl\n"
                + "$ ls\n"
                + "dir scwlmjzm\n"
                + "$ cd scwlmjzm\n"
                + "$ ls\n"
                + "119717 vhpsrbzw.jnh\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd sjdh\n"
                + "$ ls\n"
                + "43495 srwzspsl\n"
                + "$ cd ..\n"
                + "$ cd zpm\n"
                + "$ ls\n"
                + "137218 mwl.pzt\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd pbqh\n"
                + "$ ls\n"
                + "202610 dlz\n"
                + "dir vdrqc\n"
                + "$ cd vdrqc\n"
                + "$ ls\n"
                + "202958 mzzmjrt\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ppwgsp\n"
                + "$ ls\n"
                + "248541 pzvtdl.lcc\n"
                + "$ cd ..\n"
                + "$ cd qqfsb\n"
                + "$ ls\n"
                + "211390 mbtsvblj.fvh\n"
                + "241455 mwl.bzl\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd nvq\n"
                + "$ ls\n"
                + "74730 hhcfpnmg.njm\n"
                + "257109 ljpzpdbf\n"
                + "8864 zcbnwhzd.ctj\n"
                + "$ cd ..\n"
                + "$ cd zcbnwhzd\n"
                + "$ ls\n"
                + "307501 ccjp\n"
                + "dir dfgbztqr\n"
                + "dir mwl\n"
                + "248526 pmhtz\n"
                + "dir rwmzdt\n"
                + "$ cd dfgbztqr\n"
                + "$ ls\n"
                + "18261 hdb\n"
                + "dir mwl\n"
                + "dir ppmtvcj\n"
                + "$ cd mwl\n"
                + "$ ls\n"
                + "36787 hdv.vfs\n"
                + "283104 zrvbsht.fmm\n"
                + "$ cd ..\n"
                + "$ cd ppmtvcj\n"
                + "$ ls\n"
                + "208809 ljpzpdbf\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd mwl\n"
                + "$ ls\n"
                + "195369 mgfvgw\n"
                + "146522 mwl\n"
                + "78589 sfthn\n"
                + "$ cd ..\n"
                + "$ cd rwmzdt\n"
                + "$ ls\n"
                + "10176 hdb\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd fgqbpcn\n"
                + "$ ls\n"
                + "169227 dhzp\n"
                + "dir dwsgcrz\n"
                + "140391 pjjln.ngc\n"
                + "162589 ppmtvcj.ngb\n"
                + "199626 rcgbjn.wfv\n"
                + "dir snrl\n"
                + "dir vfnrs\n"
                + "$ cd dwsgcrz\n"
                + "$ ls\n"
                + "300751 fjlw.wtp\n"
                + "$ cd ..\n"
                + "$ cd snrl\n"
                + "$ ls\n"
                + "16142 ccjp.jpw\n"
                + "150389 cmbnljt.ljq\n"
                + "52600 gqggd.dwm\n"
                + "$ cd ..\n"
                + "$ cd vfnrs\n"
                + "$ ls\n"
                + "217267 bwlpdfv.hzh\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd vmdlwdj\n"
                + "$ ls\n"
                + "29199 bcgjdpj.qcj\n"
                + "172894 jjgrcd.cvf\n"
                + "dir ngpnmbqz\n"
                + "296193 ppmtvcj.bfr\n"
                + "dir tfvhhpn\n"
                + "36476 wqzst.wcj\n"
                + "$ cd ngpnmbqz\n"
                + "$ ls\n"
                + "dir gnsm\n"
                + "dir ntsgrm\n"
                + "$ cd gnsm\n"
                + "$ ls\n"
                + "dir rjzngs\n"
                + "dir tvv\n"
                + "$ cd rjzngs\n"
                + "$ ls\n"
                + "dir dpfcw\n"
                + "dir spmhrb\n"
                + "$ cd dpfcw\n"
                + "$ ls\n"
                + "181566 mgdjjd.pqg\n"
                + "$ cd ..\n"
                + "$ cd spmhrb\n"
                + "$ ls\n"
                + "163198 hhcfpnmg.njm\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd tvv\n"
                + "$ ls\n"
                + "131443 hhcfpnmg.njm\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ntsgrm\n"
                + "$ ls\n"
                + "246786 dlz\n"
                + "12841 pzbgrn\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd tfvhhpn\n"
                + "$ ls\n"
                + "196923 dhzp\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd pzg\n"
                + "$ ls\n"
                + "262706 ppbqssj.hjj\n"
                + "$ cd ..\n"
                + "$ cd thfgwwsp\n"
                + "$ ls\n"
                + "dir dsvc\n"
                + "dir fbg\n"
                + "dir flgmdj\n"
                + "516 gwppndsl\n"
                + "dir mwl\n"
                + "dir qfhsr\n"
                + "dir tgj\n"
                + "dir wdmzc\n"
                + "272804 zcbnwhzd\n"
                + "dir zrfmzrl\n"
                + "$ cd dsvc\n"
                + "$ ls\n"
                + "22089 dlz\n"
                + "$ cd ..\n"
                + "$ cd fbg\n"
                + "$ ls\n"
                + "289639 hhcfpnmg.njm\n"
                + "$ cd ..\n"
                + "$ cd flgmdj\n"
                + "$ ls\n"
                + "293793 fqrpf\n"
                + "$ cd ..\n"
                + "$ cd mwl\n"
                + "$ ls\n"
                + "159673 dhzp\n"
                + "dir ftthgr\n"
                + "270973 hhcfpnmg.njm\n"
                + "dir jjrq\n"
                + "279365 ljpzpdbf\n"
                + "dir mglzfcq\n"
                + "101769 pnz\n"
                + "18964 rdl.wqf\n"
                + "$ cd ftthgr\n"
                + "$ ls\n"
                + "dir ccrvnht\n"
                + "170369 ljltl.slv\n"
                + "dir mwl\n"
                + "dir zqts\n"
                + "65217 zvnhmqpz.cqb\n"
                + "$ cd ccrvnht\n"
                + "$ ls\n"
                + "164437 hdb\n"
                + "$ cd ..\n"
                + "$ cd mwl\n"
                + "$ ls\n"
                + "dir cjsc\n"
                + "dir zcbnwhzd\n"
                + "dir zwzb\n"
                + "$ cd cjsc\n"
                + "$ ls\n"
                + "91883 hhcfpnmg.njm\n"
                + "203008 nfmvr\n"
                + "$ cd ..\n"
                + "$ cd zcbnwhzd\n"
                + "$ ls\n"
                + "dir mbtsvblj\n"
                + "$ cd mbtsvblj\n"
                + "$ ls\n"
                + "187513 ljpzpdbf\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd zwzb\n"
                + "$ ls\n"
                + "138631 ljpzpdbf\n"
                + "dir sjngjp\n"
                + "$ cd sjngjp\n"
                + "$ ls\n"
                + "52116 ccjp.ttc\n"
                + "157900 fptzbpp.sdm\n"
                + "89462 hhcfpnmg.njm\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd zqts\n"
                + "$ ls\n"
                + "162402 hdb\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd jjrq\n"
                + "$ ls\n"
                + "dir bffvw\n"
                + "dir czbwf\n"
                + "13447 dlz\n"
                + "dir gjh\n"
                + "dir hjs\n"
                + "$ cd bffvw\n"
                + "$ ls\n"
                + "139679 dqqtq.lnb\n"
                + "dir mwl\n"
                + "13310 sjln.zgv\n"
                + "243329 srmghrt.ffl\n"
                + "72108 ssm.tph\n"
                + "$ cd mwl\n"
                + "$ ls\n"
                + "dir fdlmfjt\n"
                + "dir jms\n"
                + "122108 nqwrj\n"
                + "$ cd fdlmfjt\n"
                + "$ ls\n"
                + "75969 hdtbcsfc.vmz\n"
                + "$ cd ..\n"
                + "$ cd jms\n"
                + "$ ls\n"
                + "297556 hhcfpnmg.njm\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd czbwf\n"
                + "$ ls\n"
                + "320541 ccjp\n"
                + "$ cd ..\n"
                + "$ cd gjh\n"
                + "$ ls\n"
                + "164281 dhzp\n"
                + "286094 vjs\n"
                + "$ cd ..\n"
                + "$ cd hjs\n"
                + "$ ls\n"
                + "dir cbdzvd\n"
                + "41353 ccjp\n"
                + "dir gbs\n"
                + "114686 hdb\n"
                + "dir hmtpm\n"
                + "278709 ljpzpdbf\n"
                + "dir ppmtvcj\n"
                + "292308 zcmlbbbc.mpp\n"
                + "86096 zttwct\n"
                + "$ cd cbdzvd\n"
                + "$ ls\n"
                + "153733 dhzp\n"
                + "$ cd ..\n"
                + "$ cd gbs\n"
                + "$ ls\n"
                + "dir nfnb\n"
                + "$ cd nfnb\n"
                + "$ ls\n"
                + "dir hgm\n"
                + "$ cd hgm\n"
                + "$ ls\n"
                + "233469 ljpzpdbf\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd hmtpm\n"
                + "$ ls\n"
                + "14247 mwl\n"
                + "$ cd ..\n"
                + "$ cd ppmtvcj\n"
                + "$ ls\n"
                + "dir jcwhvcf\n"
                + "241390 mwl\n"
                + "$ cd jcwhvcf\n"
                + "$ ls\n"
                + "198254 wddq.rgp\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd mglzfcq\n"
                + "$ ls\n"
                + "dir bsplglmj\n"
                + "21700 fhflt.vgq\n"
                + "56724 lpmcbzrj\n"
                + "222733 qnbr\n"
                + "256952 thvbqb.gtv\n"
                + "$ cd bsplglmj\n"
                + "$ ls\n"
                + "dir zcbnwhzd\n"
                + "$ cd zcbnwhzd\n"
                + "$ ls\n"
                + "dir mqzqz\n"
                + "$ cd mqzqz\n"
                + "$ ls\n"
                + "75000 ppmtvcj\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd ..\n"
                + "$ cd qfhsr\n"
                + "$ ls\n"
                + "249770 gfv.cnw\n"
                + "70204 qlvwhff.jhm\n"
                + "$ cd ..\n"
                + "$ cd tgj\n"
                + "$ ls\n"
                + "243926 mwl.bfv\n"
                + "$ cd ..\n"
                + "$ cd wdmzc\n"
                + "$ ls\n"
                + "19843 hdb\n"
                + "264263 jbqf.str\n"
                + "261303 qrvt.lbr\n"
                + "$ cd ..\n"
                + "$ cd zrfmzrl\n"
                + "$ ls\n"
                + "52067 lnfgp.nhl";

        dummy.browseContent(content, directory);

        System.out.println("-----------");

        dummy.display_dir(directory);
        System.out.println("-----------");
        System.out.println(directory.totalSize10);


//        String s = "22089\n"
//                + "52067\n"
//                + "300000\n"
//                + "75969\n"
//                + "14247\n"
//                + "90381\n"
//                + "59872\n"
//                + "10176\n"
//                + "73809\n"
//                + "39489\n"
//                + "43495\n"
//                + "90698\n"
//                + "79744\n"
//                + "184125\n"
//                + "90781\n"
//                + "82162\n"
//                + "109988\n"
//                + "79532\n"
//                + "62811\n"
//                + "43177\n"
//                + "46355";
//        List<String> contentList = Arrays.asList(s.split("\n"));
//        long count = 0;
//        for (String newstring : contentList) {
//            count = count + Integer.parseInt(newstring);
//        }
//      System.out.println("result =" + count);

    }
}
