public class Main {
    public static void main(String[] args) {
        Dummy dummy = new Dummy();
        String content = "addx 1\n"
                + "noop\n"
                + "noop\n"
                + "addx 4\n"
                + "addx 5\n"
                + "addx -2\n"
                + "addx 19\n"
                + "addx -12\n"
                + "addx 3\n"
                + "addx -2\n"
                + "addx 4\n"
                + "noop\n"
                + "noop\n"
                + "noop\n"
                + "addx 3\n"
                + "addx -8\n"
                + "addx 15\n"
                + "addx 1\n"
                + "noop\n"
                + "noop\n"
                + "addx 6\n"
                + "addx -1\n"
                + "noop\n"
                + "addx -38\n"
                + "noop\n"
                + "addx 10\n"
                + "addx -5\n"
                + "noop\n"
                + "addx 3\n"
                + "addx 2\n"
                + "addx 7\n"
                + "noop\n"
                + "noop\n"
                + "addx 3\n"
                + "noop\n"
                + "addx 2\n"
                + "addx 3\n"
                + "addx -2\n"
                + "addx 2\n"
                + "addx 7\n"
                + "noop\n"
                + "noop\n"
                + "addx 9\n"
                + "noop\n"
                + "addx -12\n"
                + "noop\n"
                + "addx 11\n"
                + "addx -38\n"
                + "noop\n"
                + "noop\n"
                + "noop\n"
                + "addx 5\n"
                + "addx 5\n"
                + "noop\n"
                + "noop\n"
                + "noop\n"
                + "addx 3\n"
                + "addx -12\n"
                + "addx 14\n"
                + "noop\n"
                + "addx 1\n"
                + "addx 3\n"
                + "addx 1\n"
                + "addx 5\n"
                + "addx 4\n"
                + "addx 1\n"
                + "noop\n"
                + "noop\n"
                + "noop\n"
                + "noop\n"
                + "noop\n"
                + "addx -9\n"
                + "addx 17\n"
                + "addx -39\n"
                + "addx 38\n"
                + "addx -8\n"
                + "addx -26\n"
                + "addx 3\n"
                + "addx 4\n"
                + "addx 16\n"
                + "noop\n"
                + "addx -11\n"
                + "addx 3\n"
                + "noop\n"
                + "addx 2\n"
                + "addx 3\n"
                + "addx -2\n"
                + "addx 2\n"
                + "noop\n"
                + "addx 13\n"
                + "addx -8\n"
                + "noop\n"
                + "addx 7\n"
                + "addx -5\n"
                + "addx 8\n"
                + "addx -40\n"
                + "addx 16\n"
                + "addx -9\n"
                + "noop\n"
                + "addx -7\n"
                + "addx 8\n"
                + "addx 2\n"
                + "addx 7\n"
                + "noop\n"
                + "noop\n"
                + "addx -15\n"
                + "addx 16\n"
                + "addx 2\n"
                + "addx 5\n"
                + "addx 2\n"
                + "addx -20\n"
                + "addx 12\n"
                + "addx 11\n"
                + "addx 8\n"
                + "addx -1\n"
                + "addx 3\n"
                + "noop\n"
                + "addx -39\n"
                + "addx 2\n"
                + "noop\n"
                + "addx 5\n"
                + "noop\n"
                + "noop\n"
                + "noop\n"
                + "addx 4\n"
                + "addx 1\n"
                + "noop\n"
                + "noop\n"
                + "addx 2\n"
                + "addx 5\n"
                + "addx 2\n"
                + "addx 1\n"
                + "addx 4\n"
                + "addx -1\n"
                + "addx 2\n"
                + "noop\n"
                + "addx 2\n"
                + "noop\n"
                + "addx 8\n"
                + "noop\n"
                + "noop\n"
                + "noop\n"
                + "addx -10\n"
                + "noop\n"
                + "noop";
        int i = dummy.compute(content);
    }
}
